# Generated by Django 5.2.15 on 2026-07-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_forum', 'Pode moderar o fórum')]},
        ),
    ]
