# Generated by Django 5.2.15 on 2026-07-07 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('xp_max', models.PositiveIntegerField(default=2000)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('avatar_color', models.CharField(default='#6b7cff', max_length=9)),
                ('achievements', models.PositiveIntegerField(default=0)),
                ('friends', models.PositiveIntegerField(default=0)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
