# Generated by Django 5.2.15 on 2026-07-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=10),
        ),
    ]
