# Generated by Django 5.2.15 on 2026-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_kinds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
