"""perfil do usuario

Revision ID: 2a91e40afabf
Revises: 2355222d72de
Create Date: 2026-08-15 16:13:08.785123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a91e40afabf'
down_revision = '2355222d72de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('xp_max', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=280), nullable=False),
    sa.Column('avatar_color', sa.String(length=9), nullable=False),
    sa.Column('achievements', sa.Integer(), nullable=False),
    sa.Column('friends', sa.Integer(), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('push_kinds', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
