"""nome_busca em jogos

Revision ID: 4dde48b0e849
Revises: 94bfd0eafbfa
Create Date: 2026-08-22 21:42:19.338282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dde48b0e849'
down_revision = '94bfd0eafbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_busca', sa.String(length=200), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_jogos_nome_busca'), ['nome_busca'], unique=False)

    # ### end Alembic commands ###

    # Backfill: a coluna é derivada, então as linhas que já existem
    # precisam dela preenchida. Sem isto a busca não acha nenhum jogo
    # do catálogo atual, e o sintoma é "a busca não funciona", não um erro.
    import unicodedata

    conexao = op.get_bind()
    linhas = conexao.execute(sa.text("SELECT id, nome FROM jogos")).fetchall()
    for identificador, nome in linhas:
        decomposto = unicodedata.normalize("NFKD", nome or "")
        # Trunca em 200: casefold() EXPANDE alguns caracteres ('ß' vira
        # 'ss'), então um nome de 200 caracteres pode gerar mais de 200
        # aqui -- e a coluna é String(200). Mesmo corte de
        # normalizar_busca (app/services/jogo_service.py); duplicado
        # porque migração não importa código da aplicação.
        normalizado = "".join(
            c for c in decomposto if not unicodedata.combining(c)
        ).casefold().strip()[:200]
        conexao.execute(
            sa.text("UPDATE jogos SET nome_busca = :v WHERE id = :i"),
            {"v": normalizado, "i": identificador},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jogos_nome_busca'))
        batch_op.drop_column('nome_busca')

    # ### end Alembic commands ###
