"""schema inicial: 22 tabelas

Revision ID: 94bfd0eafbfa
Revises: 
Create Date: 2026-08-22 02:18:24.748826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bfd0eafbfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('icone_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('iniciais', sa.String(length=4), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sobre', sa.Text(), nullable=True),
    sa.Column('merch', sa.Text(), nullable=True),
    sa.Column('classificacao', sa.String(length=10), nullable=True),
    sa.Column('desenvolvedora', sa.String(length=200), nullable=True),
    sa.Column('publicadora', sa.String(length=200), nullable=True),
    sa.Column('data_lancamento', sa.String(length=60), nullable=True),
    sa.Column('metacritic', sa.SmallInteger(), nullable=True),
    sa.Column('capa_url', sa.Text(), nullable=True),
    sa.Column('arquivo_capa', sa.String(length=255), nullable=True),
    sa.Column('capa_gradiente', sa.JSON(), nullable=True),
    sa.Column('popularidade', sa.Integer(), nullable=False),
    sa.Column('curtidas', sa.Integer(), nullable=False),
    sa.Column('descurtidas', sa.Integer(), nullable=False),
    sa.Column('conquistas', sa.Integer(), nullable=False),
    sa.Column('tempo_medio', sa.String(length=40), nullable=True),
    sa.Column('tempo_speedrun', sa.String(length=40), nullable=True),
    sa.Column('tempo_platina', sa.String(length=40), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('plataformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('xp_max', sa.Integer(), nullable=False),
    sa.Column('cor_avatar', sa.String(length=9), nullable=False),
    sa.Column('conquistas', sa.Integer(), nullable=False),
    sa.Column('amigos', sa.Integer(), nullable=False),
    sa.Column('dias_ativo', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biblioteca_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('favorito', sa.Boolean(), nullable=False),
    sa.Column('minutos_jogados', sa.Integer(), nullable=False),
    sa.Column('progresso', sa.SmallInteger(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'jogo_id')
    )
    op.create_table('bugometro_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogo_id')
    )
    op.create_table('historico_bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_crash', sa.Integer(), nullable=True),
    sa.Column('quantidade_bug', sa.Integer(), nullable=True),
    sa.Column('quantidade_fps_drop', sa.Integer(), nullable=True),
    sa.Column('quantidade_stutter', sa.Integer(), nullable=True),
    sa.Column('registrado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogos_generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogo_id', 'genero_id')
    )
    op.create_table('jogos_plataformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('plataforma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('severidade', sa.String(length=20), nullable=True),
    sa.Column('porcentagem', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatos_bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=True),
    sa.Column('confirmacoes', sa.Integer(), nullable=False),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('jogo_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('conquistado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'badge_id')
    )
    op.create_table('curtidas_avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'usuario_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('oculto', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos_bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relato_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['relato_id'], ['relatos_bug.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relato_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos_bug')
    op.drop_table('posts')
    op.drop_table('curtidas_avaliacoes')
    op.drop_table('usuarios_badges')
    op.drop_table('topicos')
    op.drop_table('relatos_bug')
    op.drop_table('notificacoes')
    op.drop_table('metricas_bug')
    op.drop_table('jogos_plataformas')
    op.drop_table('jogos_generos')
    op.drop_table('historico_bug')
    op.drop_table('bugometro_status')
    op.drop_table('biblioteca_usuario')
    op.drop_table('avaliacoes')
    op.drop_table('atividades')
    op.drop_table('alertas')
    op.drop_table('usuarios')
    op.drop_table('plataformas')
    op.drop_table('jogos')
    op.drop_table('generos')
    op.drop_table('categorias')
    op.drop_table('badges')
    # ### end Alembic commands ###
