"""senha_alterada_em e versao_sessao em usuarios

Revision ID: c65ff4e88981
Revises: 4dde48b0e849
Create Date: 2026-08-22 22:58:18.642008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65ff4e88981'
down_revision = '4dde48b0e849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_alterada_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('versao_sessao', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('versao_sessao')
        batch_op.drop_column('senha_alterada_em')

    # ### end Alembic commands ###
