# Generated by Django 5.2.15 on 2026-07-07 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('steam_appid', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('merch', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('cover', models.JSONField(blank=True, default=list)),
                ('cover_file', models.ImageField(blank=True, upload_to='covers/')),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('bug_score', models.PositiveSmallIntegerField(default=0)),
                ('release_date', models.CharField(blank=True, max_length=60)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('metacritic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('achievements', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('time_to_beat_main', models.CharField(blank=True, max_length=40)),
                ('time_to_beat_speedrun', models.CharField(blank=True, max_length=40)),
                ('time_to_beat_platinum', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='catalog.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('owners', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('fetching', 'Buscando'), ('done', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank', 'appid'],
                'indexes': [models.Index(fields=['status'], name='catalog_ing_status_12ea0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='catalog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'library entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['bug_score'], name='catalog_gam_bug_sco_a6e8f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryentry',
            unique_together={('user', 'game')},
        ),
    ]
