# Generated by Django 5.2.15 on 2026-07-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'permissions': [('can_moderate_games', 'Pode moderar jogos/bugs')]},
        ),
    ]
