# Generated by Django 5.2.15 on 2026-07-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
