# Generated by Django 5.2.15 on 2026-07-08 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_game_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('crash', 'Crash'), ('graphics', 'Gráficos'), ('performance', 'Desempenho'), ('progression', 'Progressão'), ('online', 'Online'), ('other', 'Outro')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('confirmed', 'Confirmado'), ('resolved', 'Resolvido'), ('rejected', 'Rejeitado')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('community', 'Comunidade'), ('scraped', 'Coletado'), ('agent', 'Agente')], default='community', max_length=20)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='catalog.game')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('crash', 'Crash'), ('graphics', 'Gráficos'), ('performance', 'Desempenho'), ('progression', 'Progressão'), ('online', 'Online'), ('other', 'Outro')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bugs.bug')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='catalog.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bugs.bug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_score', models.PositiveSmallIntegerField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='catalog.game')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['game', 'status'], name='bugs_bug_game_id_8f0fb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bugvote',
            unique_together={('bug', 'user')},
        ),
        migrations.AddIndex(
            model_name='gamescoresnapshot',
            index=models.Index(fields=['game', 'captured_at'], name='bugs_gamesc_game_id_da2052_idx'),
        ),
    ]
