# Generated by Django 5.2.15 on 2026-07-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('community', 'Comunidade'), ('scraped', 'Coletado'), ('agent', 'Agente')], default='scraped', max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='bugs.bug')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
